import type { LucideIcon } from 'lucide-react-native';
import {
  Activity,
  ArrowRight,
  Camera,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Copy,
  Download,
  Eye,
  EyeOff,
  ImageIcon,
  ImagePlus,
  KeyRound,
  LayoutGrid,
  ListChecks,
  LocateFixed,
  Navigation,
  Pencil,
  Plus,
  RefreshCw,
  Rows3,
  SearchCheck,
  Share2,
  SlidersHorizontal,
  Trash2,
  X,
} from 'lucide-react-native';
import {
  AlertRealIcon,
  BellRealIcon,
  BriefcaseRealIcon,
  BuildingRealIcon,
  CalendarRealIcon,
  CardRealIcon,
  ChartRealIcon,
  CheckRealIcon,
  ClipboardRealIcon,
  ClockRealIcon,
  CloudSunRealIcon,
  CockroachIcon,
  DashboardRealIcon,
  ErrorRealIcon,
  FactoryRealIcon,
  FileRealIcon,
  GiftRealIcon,
  HomeRealIcon,
  HotelRealIcon,
  InfoRealIcon,
  LeafRealIcon,
  LockRealIcon,
  LogoutRealIcon,
  MailRealIcon,
  MessageRealIcon,
  OfferRealIcon,
  OfflineRealIcon,
  PackageRealIcon,
  PercentRealIcon,
  PhoneDeviceRealIcon,
  PhoneRealIcon,
  PinRealIcon,
  AddressRealIcon,
  FaqBookRealIcon,
  ChatRealIcon,
  RupeeRealIcon,
  SearchRealIcon,
  SettingsRealIcon,
  ShieldRealIcon,
  SprayIcon,
  StarRealIcon,
  StoreRealIcon,
  SunRealIcon,
  SupportRealIcon,
  TagsRealIcon,
  TechRealIcon,
  UserPlusRealIcon,
  UserRealIcon,
  UsersRealIcon,
  WalletRealIcon,
  WarehouseRealIcon,
} from '@/components/icons/RealIcons';

/** Shared gradient fills for premium icon tiles. */
export const IconGradients = {
  forest: ['#30B84F', '#1B873E', '#043813'] as const,
  gold: ['#B6E86A', '#8FD03C', '#27A747'] as const,
  lime: ['#A8E05A', '#8FD03C', '#1A8734'] as const,
  teal: ['#3FBF62', '#1B873E', '#0A6423'] as const,
  mint: ['#F4FBF0', '#EAF6E3', '#CFEACF'] as const,
  soft: ['#FFFFFF', '#F6FAF2', '#EAF6E3'] as const,
  danger: ['#E07A4F', '#C15B31', '#9E3F1C'] as const,
  verify: ['#30B84F', '#1B873E', '#043813'] as const,
  ring: ['#8FD03C', '#27A747', '#1B873E'] as const,
};

/** Pest-control themed icons — realistic custom SVGs + Lucide chrome. */
export const AppIcons = {
  brand: SprayIcon,
  empty: CockroachIcon,

  customerTab: {
    home: HomeRealIcon,
    bookings: ClipboardRealIcon,
    offers: OfferRealIcon,
    profile: UserRealIcon,
  } satisfies Record<string, LucideIcon>,

  adminTab: {
    dashboard: DashboardRealIcon,
    bookings: ClipboardRealIcon,
    team: TechRealIcon,
    reports: ChartRealIcon,
  } satisfies Record<string, LucideIcon>,

  techTab: {
    jobs: PackageRealIcon,
    profile: TechRealIcon,
  } satisfies Record<string, LucideIcon>,

  quick: {
    book: SprayIcon,
    bookings: CalendarRealIcon,
    offers: OfferRealIcon,
    support: SupportRealIcon,
  } satisfies Record<string, LucideIcon>,

  techHub: {
    jobs: ClipboardRealIcon,
    active: BriefcaseRealIcon,
    verify: ShieldRealIcon,
    allJobs: CalendarRealIcon,
  } satisfies Record<string, LucideIcon>,

  techStats: {
    assigned: BriefcaseRealIcon,
    active: ClockRealIcon,
    verify: ShieldRealIcon,
    done: CheckRealIcon,
    earnings: RupeeRealIcon,
    rating: StarRealIcon,
  } satisfies Record<string, LucideIcon>,

  techAlert: {
    verify: ShieldRealIcon,
    overdue: AlertRealIcon,
  } satisfies Record<string, LucideIcon>,

  techProfile: {
    verified: CheckRealIcon,
    location: PinRealIcon,
    phone: PhoneRealIcon,
    logout: LogoutRealIcon,
  } satisfies Record<string, LucideIcon>,

  adminQuick: {
    bookings: ClipboardRealIcon,
    services: SprayIcon,
    addTech: UserPlusRealIcon,
    offers: TagsRealIcon,
    content: FileRealIcon,
    team: TechRealIcon,
  } satisfies Record<string, LucideIcon>,

  adminKpi: {
    pending: ClockRealIcon,
    bookings: ClipboardRealIcon,
    active: SprayIcon,
    customers: UsersRealIcon,
  } satisfies Record<string, LucideIcon>,

  adminHub: {
    homeContent: HomeRealIcon,
    services: SprayIcon,
    offers: TagsRealIcon,
    reviews: MessageRealIcon,
    users: ShieldRealIcon,
    technicians: TechRealIcon,
    customers: UserRealIcon,
  } satisfies Record<string, LucideIcon>,

  contentTab: {
    promo: TagsRealIcon,
    home: HomeRealIcon,
    brand: ShieldRealIcon,
    booking: CalendarRealIcon,
    screens: UserRealIcon,
    onboard: SprayIcon,
    legal: ShieldRealIcon,
  } satisfies Record<string, LucideIcon>,

  trust: {
    verified: ShieldRealIcon,
    sameDay: ClockRealIcon,
    eco: LeafRealIcon,
  } satisfies Record<string, LucideIcon>,

  notification: {
    admin: ClipboardRealIcon,
    booking: CalendarRealIcon,
    complete: ShieldRealIcon,
    default: BellRealIcon,
  } satisfies Record<string, LucideIcon>,

  profile: {
    bookings: ClipboardRealIcon,
    addresses: AddressRealIcon,
    payments: CardRealIcon,
    offers: OfferRealIcon,
    notifications: BellRealIcon,
    help: SupportRealIcon,
    faq: FaqBookRealIcon,
    about: InfoRealIcon,
    terms: FileRealIcon,
    privacy: ShieldRealIcon,
    settings: SettingsRealIcon,
    chat: ChatRealIcon,
    call: PhoneRealIcon,
    logout: LogoutRealIcon,
  } satisfies Record<string, LucideIcon>,

  property: {
    home: HomeRealIcon,
    apartment: BuildingRealIcon,
    hotel: HotelRealIcon,
    store: StoreRealIcon,
    warehouse: WarehouseRealIcon,
    factory: FactoryRealIcon,
  } satisfies Record<string, LucideIcon>,

  payment: {
    card: CardRealIcon,
    wallet: WalletRealIcon,
    upi: PhoneDeviceRealIcon,
  } satisfies Record<string, LucideIcon>,

  toast: {
    success: CheckRealIcon,
    error: ErrorRealIcon,
    warn: AlertRealIcon,
    info: InfoRealIcon,
    offline: OfflineRealIcon,
  } satisfies Record<string, LucideIcon>,

  ui: {
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    arrowRight: ArrowRight,
    plus: Plus,
    close: X,
    camera: Camera,
    check: CheckRealIcon,
    image: ImageIcon,
    imagePlus: ImagePlus,
    edit: Pencil,
    mail: MailRealIcon,
    user: UserRealIcon,
    wallet: WalletRealIcon,
    calendar: CalendarRealIcon,
    calendarCheck: CalendarRealIcon,
    calendarClock: CalendarRealIcon,
    clock: ClockRealIcon,
    mapPin: PinRealIcon,
    mapPinned: AddressRealIcon,
    bell: BellRealIcon,
    settings: SettingsRealIcon,
    logout: LogoutRealIcon,
    info: InfoRealIcon,
    terms: FileRealIcon,
    search: SearchRealIcon,
    searchCheck: SearchCheck,
    pay: RupeeRealIcon,
    eye: Eye,
    eyeOff: EyeOff,
    lock: LockRealIcon,
    phone: PhoneRealIcon,
    phoneCall: PhoneRealIcon,
    message: ChatRealIcon,
    help: SupportRealIcon,
    copy: Copy,
    share: Share2,
    refresh: RefreshCw,
    download: Download,
    tag: TagsRealIcon,
    percent: PercentRealIcon,
    star: StarRealIcon,
    leaf: LeafRealIcon,
    shield: ShieldRealIcon,
    shieldCheck: ShieldRealIcon,
    sparkles: SprayIcon,
    gift: GiftRealIcon,
    key: KeyRound,
    listChecks: ListChecks,
    layoutGrid: LayoutGrid,
    rows: Rows3,
    filters: SlidersHorizontal,
    locate: LocateFixed,
    navigation: Navigation,
    activity: Activity,
    alert: AlertRealIcon,
    trash: Trash2,
    sun: SunRealIcon,
    cloudSun: CloudSunRealIcon,
    bug: CockroachIcon,
    brand: SprayIcon,
    rupee: RupeeRealIcon,
  } satisfies Record<string, LucideIcon>,
};

export type AppIconName = LucideIcon;
